### ISSUE TITLE
multi-cluster for exporter

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#235]
# description:

We want to use exporters in multi-cluster scenario see (https://trello.com/c/WOAtM6kU/1066-haclusterexporter-research-the-functionality-of-exporter-multi-cluster-scenario)

 like `ha_cluster_exporter` in different cluster.

We can solve the problem in a easy fashion like following:

![image](https://user-images.githubusercontent.com/10886597/67582005-41324e80-f749-11e9-9ff9-628054d72c8a.png)

As you can see, prometheus for each metric add the `job` label. We just need to map this to our cluster. See later for pragmatic approach

# Solution:

the solution is simple. we need to call different jobs accordingly to the cluster. This will be the ID for creating mapping between exporter and cluster. See pictures. So you can filter 
Prometheus will then create a label for each different jobs name. 

`/etc/prometheus/prometheus.yaml`

```
  - job_name: cluster-europe-00
    metrics_path: /metrics
    static_configs:
      - targets:
        - "192.168.110.19:9002" # 9002: ha_cluster_exporter metrics
        - "192.168.110.20:9002" # 9002: ha_cluster_exporter metrics

  - job_name: cluster-asia-00
    metrics_path: /metrics
    static_configs:
      - targets:
        - "10.67.162.43:9002"
```
