### ISSUE TITLE
sle12sp4 deployment fail to install iscsi formula (hana only)

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#399]
@arbulu89 cc

so I'm trying to deploy on sle12sp4 but it fails with 

```
Problem: nothing provides salt-formulas-configuration needed by iscsi-formula-1.1.1-410.1.1.develHead.noarch
 Solution 1: do not install iscsi-formula-1.1.1-410.1.1.develHead.noarch
 Solution 2: break iscsi-formula-1.1.1-410.1.1.develHead.noarch by ignoring some of its dependencies

```

```
es:   
----------
          ID: iscsi-formula
    Function: pkg.installed
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: Running scope as unit run-ra7f2572d48534b3eb814289a3e532262.scope."
              Attempt 2: Returned a result of "False", with the following comment: "An error was encountered while installing package(s): Zypper command failure: Running scope as unit run-r4ef91e6727374129bb77900f9b160ada.scope."
              An error was encountered while installing package(s): Zypper command failure: Running scope as unit run-rb0e296e1c01a46cf8673332fb16fe862.scope.
     Started: 18:17:27.639484
    Duration: 35328.477 ms
     Changes:   
----------
```

```
base_image = &quot;http://download.suse.de/ibs/Devel:/SAP:/Terraform:/Images/images/SLES4SAP-12SP4-JeOS.x86_64.qcow2&quot;
ha_sap_deployment_repo = "http://download.opensuse.org/repositories/network:/ha-clustering:/Unstable/SLE_12_SP4/"
```
