### ISSUE TITLE
AWS HANA Install Directory Permission

### ISSUE THREAD

**Issue by ab-mohamed** [SUSE/ha-sap-terraform-deployments#527]
Hi, 

### The Issue 
Using SAP HANA 2.0 SPS04 for AWS to deploy SAP HANA HA cluster was failed and it produced the following error messages:
```
$ terraform apply
[...]
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): [INFO    ] {'method': 'update', 'url': '/tmp/cluster.config'}
module.hana_node.module.hana_provision.null_resource.provision[1] (remote-exec): [INFO    ] Completed state [update] at time 09:18:57.753628 (duration_in_ms=510.743)

Error: error executing "/tmp/terraform_614846754.sh": Process exited with status 1
Error: error executing "/tmp/terraform_373864149.sh": Process exited with status 1
```

### The Troubleshooting Steps

1. The `salt-deployment.log` log file shows the following error messages:
```
hana01:~ # grep ERROR /var/log/salt-deployment.log
[....]
 4 2020-09-02 09:17:55,283 [shaptools.shell  :56  ][ERROR   ][4187]     /sapmedia/HANA/DATA_UNITS/HDB_SERVER_LINUX_X86_64
  5 2020-09-02 09:17:55,283 [shaptools.shell  :56  ][ERROR   ][4187]     /sapmedia/HANA/DATA_UNITS/HDB_CLIENT_LINUX_X86_64
  6 2020-09-02 09:17:55,283 [shaptools.shell  :56  ][ERROR   ][4187]   Ensure that no permissions are changed by the umask when extracting or copying the folders.
[...]
```

2. Check the above-mentioned dirs permissions:
```
hana01:~ # ls -lhd /sapmedia/HANA/DATA_UNITS/HDB_SERVER_LINUX_X86_64
drwxr-xr-- 8 root root 4.0K Sep  2 11:26 /sapmedia/HANA/DATA_UNITS/HDB_SERVER_LINUX_X86_64
hana01:~ # ls -lhd /sapmedia/HANA/DATA_UNITS/HDB_CLIENT_LINUX_X86_64
drwxr-xr-- 5 root root 188 Sep  2 11:26 /sapmedia/HANA/DATA_UNITS/HDB_CLIENT_LINUX_X86_64
```

3. Change the `/sapmedia/HANA` dir permission:
```
hana01:~ # chmod -R 755 /sapmedia/HANA
```

4. Run HANA installer manually:

4.1. Prepare for the HANA installer: 
```
hana01:~ #  /sapmedia/HANA/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm --action=install --dump_configfile_template=/tmp/hana.conf
```

4.2. Set the SID name in `/tmp/hana.conf.xml` file

4.3. Replace the `***` in `/root/hdb_passwords.xml` by your password.

4.4 Run the HANA installer:
```
hana01:~ # cat /root/hdb_passwords.xml | /sapmedia/HANA/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm -b --read_password_from_stdin=xml --configfile=/tmp/hana.conf
```
It worked fine.

### The Proposal Fix
In `ha-sap-terraform-deployments/salt/hana_node/download_hana_inst.sls` file, change the dir mode from `0754` to `0755`.

Before:
```
{{ grains['hana_inst_folder'] }}:
  file.directory:
    - user: root
    - group: root
    - dir_mode: "0754"
    - file_mode: "0755"
    - recurse:
      - user
      - group
      - mode
```

After:
```
{{ grains['hana_inst_folder'] }}:
  file.directory:
    - user: root
    - group: root
    - dir_mode: "0755"
    - file_mode: "0755"
    - recurse:
      - user
      - group
      - mode
```

Kudos to @arbulu89 for guiding me through the troubleshooting steps.
