### ISSUE TITLE
cleanup grafana file state

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#601]
# Description:

currenlty we do have 3 states which append things.

we should find replace the commented conf in order to avoid this 

```
[auth.anonymous]
enabled = true
# enable anonymous access
;enabled = false```

**Comment by stefanotorresi** [comment]
Hmm, I don't quite get why are you proposing to change the matching.

Changing a commented setting is much harder than just adding a new line!

**Comment by MalloZup** [comment]
yes this is true but is more cleaner the config file.


```
allow_pam_caching_oneday:
  file.replace:
    - name: '/etc/sssd/sssd.conf'
    - pattern: {{ '[pam]' | regex_escape }}
    - repl: '\g<0>\noffline_credentials_expiration = 1'
    - require:
      - cmd: join_domain
      - file: allow_pam_caching_oneday_cleanup

```

or we can have grafana.ini file managed, that is more easy in case.
