### ISSUE TITLE
Grafana: Netweaver Dashboard do not work

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#611]
I'm testing the deployment of SAP NW750 + Monitoring (Grafana & Prometheus)
Deployment finishes well. No errors.
Everything works fine, but the GRAFANA Dashboard related to SAP Netweaver does not work.
Show No-data
HANA Dashboard its Ok

Checking into Prometheus page I have ALL the Netweaver endpoint DOWN (see attach)
And the error is:
Get "http://10.0.1.10:9664/metrics": dial tcp 10.0.1.10:9664: connect: connection refused
and
Get "http://192.168.1.30:9100/metrics": context deadline exceeded
![Screenshot_100](https://user-images.githubusercontent.com/23618664/101201080-7953d280-3667-11eb-9329-1a50307bf796.jpg)

**Comment by MalloZup** [comment]
@picoroma  thx for issue! in which cloud are you running this? AWS?

It could be that the ports are not open or some security policy on cloud is causing this. ( on azure for example we do have security rules for this)
let me know tia

**Comment by picoroma** [comment]
Yes, I'm on AWS.
I checked the SG. THe 1st think I verified...
The AllTraffic Rule is in place for host involved (all 10.0.0.0/16 subnet) and also from MY IP
I will perform some more test..
maybe the 192.168.xxx.yyy was missing...

P.

**Comment by picoroma** [comment]
I repeated the test.
The problem seems to be related to traffic from "Monitoring host" to netweaver host.
But, the SG is quite OPEN...
But if I telnet from monitoring host to netweaver host using 192.168.xxx.yyy IP (virtual IP) - telnet fails. See attached images.
If i Use 10.0.2.30 IP (real IP) - Telnet works!

![Screenshot_101](https://user-images.githubusercontent.com/23618664/101261251-11b88880-3736-11eb-8885-ff622f89bb27.jpg)
![Screenshot_102](https://user-images.githubusercontent.com/23618664/101261254-1bda8700-3736-11eb-9aff-c612742df9f7.jpg)
![Screenshot_103](https://user-images.githubusercontent.com/23618664/101261255-2006a480-3736-11eb-9188-78297348becc.jpg)

**Comment by MalloZup** [comment]
thx @picoroma . I will note this , so we can investigate further.

**Comment by stefanotorresi** [comment]
This seems to also affects Azure, pending confirmation.

**Comment by yeoldegrove** [comment]
I experienced #707 when trying to reproduce this.

**Comment by yeoldegrove** [comment]
> This seems to also affects Azure, pending confirmation.
I can confirm this.

**Comment by yeoldegrove** [comment]
Within #710 are fixes to differentiate between host, ha and application/vip exporter hosts:ports.

new targets:
```
monitoring:~ # cat /etc/prometheus/prometheus.yml
[...]
  - job_name: netweaver
    static_configs:
      - targets:
        - "10.0.3.30:9100" # node_exporter
        - "10.0.4.31:9100" # node_exporter
        - "10.0.3.32:9100" # node_exporter
        - "10.0.4.33:9100" # node_exporter
        - "10.0.3.30:9664" # ha_cluster_exporter
        - "10.0.4.31:9664" # ha_cluster_exporter
        - "192.168.1.30:9680" # sap_host_exporter
        - "192.168.1.31:9680" # sap_host_exporter
        - "192.168.1.32:9680" # sap_host_exporter
        - "192.168.1.33:9680" # sap_host_exporter
```

With this new configuration, everything works on my test systems for AWS + Azure.
